config/routes.rb
SPIN::Application.routes.draw do
  
  resources :property_ranges
  resources :profiles
  resources :units
  resources :categories
  resources :properties
  resources :items

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :property_ranges
      resources :profiles
      resources :units
      resources :categories
      resources :properties
      resources :items do
        post 'search', :on => :collection
        post 'navigate', :on => :collection
      end 

    end
  end

  

  root :to => 'pages#index'

  match 'index' => 'pages#index'
  match 'about' => 'pages#about'    
  
end

app/models/property.rb
class Property < ActiveRecord::Base
  attr_accessible :name, :description, :value_type, :unit, :unit_id
          
  has_many :property_valuations, :dependent => :destroy  
  has_many :items, :through => :property_valuations
  has_many :property_ranges, :dependent => :destroy

  belongs_to :unit
  
  # validations
  validates :name, :value_type, :unit, :presence => true
  validates :name, :uniqueness => true

  # exclude fields from json output

  def as_json(options={})
    options[:except] ||= [:created_at, :updated_at]
    options[:include] ||= [:unit]
    super(options)
  end 

  #def as_json(options={})
  #  {:id => self.id,
  #   :name => self.name,
  #   :description => self.description,
  #   :value_type => self.value_type,
  #   :unit_id => self.unit_id
  # }
  #end

end

app/controllers/api/v1/properties_controller.rb
module Api
  module V1
    class PropertiesController < ApplicationController
      
      respond_to :json

      def index
        @properties = Property.all   
        
        render :json => { 
          :statusCode => 0, 
          :statusMessage => 'Sucess', 
          :properties => @properties.as_json(:include => { :unit => { :except  => [:id, :created_at, :updated_at] } })
        }
        
      end
      
      def show
        begin
          @property = Property.find(params[:id])
        rescue ActiveRecord::RecordNotFound
          respond_with( {
            :statusCode => 1,
            :statusMessage => "Failed to get property"
          })
        end
      end   
       
    end
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  
  def index
    @properties = Property.all
  end
  
  def show
    @property = Property.find(params[:id])
  end    
  
  def new
    @property = Property.new    
    @possible_types = %w[Numeric Text]
  end 
    
  def create
    @property = Property.new(params[:property])
    @possible_types = %w[Numeric Text]
    if @property.save
      flash[:notice] = "Property has been created."
      redirect_to properties_path
    else
      flash[:alert] = "Property has not been created."
      render :action => "new"
    end
  end
  
  def edit
    @property = Property.find(params[:id])
    @possible_types = %w[Numeric Text]
  end
  
  def update        
    @property = Property.find(params[:id])
    @possible_types = %w[Numeric Text]
        
    if @property.update_attributes(params[:property])
      flash[:notice] = "Property has been updated"
      redirect_to properties_path
    else
      flash[:alert] = "Property has not been updated"
      render :action => "edit"
    end
  end   
  
  def destroy
    @property = Property.find(params[:id])
    
    @property.destroy
    flash[:notice] = "Property has been deleted."
    redirect_to properties_path
  end
  
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= form_for(@property) do |f| %>
<% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% @property.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<p>
		<%= f.label :name, "Property name" %>
		<%= f.text_field :name %>
	</p>
	
	<p>
		<%= f.label :description, "Description" %>
		<%= f.text_area :description, :size => "50x6", :class => 'span12' %>
	</p>
	
	<p>
		<%= f.label :value_type, "Value Type" %>
		<%= f.select :value_type, @possible_types %>
	</p>
	
	<p>
		<%= f.label :unit, "Unit" %>
    <%= f.select :unit_id, Unit.all.collect { |unit| [unit.name, unit.id] } %>
	</p>
	
	<%= f.submit :class => 'btn btn-success' %>
	<%= link_to 'Cancel', properties_path, :data => { :confirm => 'Are you sure you want to leave this page?' }, :class => 'btn btn-danger' %>

<% end %>

app/views/properties/edit.html.erb
<h2>Edit Property</h2>

<hr />

<%= render "form" %>

app/views/properties/index.html.erb
<h2>Properties</h2>

<hr />

<%= link_to "New Property", new_property_path, :class => 'btn btn-primary' %>

<br /><br />

<% if @properties.any? %>
    <table class="table table-striped">
        <tr>            
            <th>Name</th>
            <th>Type</th>
            <th>Units</th>
            <th colspan="3">Options</th>
        </tr>
    
        <% @properties.each do |property| %>
            <tr>                
                <td><%= property.name %></td>
                <td><%= property.value_type %></td>
                <td><%= property.unit.name %></td>
                <td><%= link_to '', property_path(property), :class => 'icon-eye-open' %></td>
                <td><%= link_to '', edit_property_path(property), :class => 'icon-pencil' %></td>
                <td><%= link_to '', property, :method => :delete, 
                        :data => { :confirm => "Are you sure you want to delete this property?" }, :class => 'icon-remove' %></td>

            </tr>
        <% end %>
    
    </table>
<% else %>
    <p>There are no properties yet.</p>
<% end %>

app/views/properties/new.html.erb
<h2>New Property</h2>

<hr />

<%= render "form" %>

app/views/properties/show.html.erb
<h2>Property</h2>
<h2>Property</h2>

<p><%= @property.name %></p>
<p><%= @property.description %></p>
<p><%= @property.value_type %></p>
<p><%= @property.unit %></p>

<%= link_to "Edit Property", edit_property_path(@property), :class => 'btn btn-primary' %>
<%= link_to "Delete Property", @property, :method => :delete, :class => 'btn btn-danger',
    :data => { :confirm => 'Are you sure you want to delete this property?' } %>