config/routes.rb
SPIN::Application.routes.draw do
  
  resources :property_ranges
  resources :profiles
  resources :units
  resources :categories
  resources :properties
  resources :items

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :property_ranges
      resources :profiles
      resources :units
      resources :categories
      resources :properties
      resources :items do
        post 'search', :on => :collection
        post 'navigate', :on => :collection
      end 

    end
  end

  

  root :to => 'pages#index'

  match 'index' => 'pages#index'
  match 'about' => 'pages#about'    
  
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :name, :description, :property_valuations, :barcode
  
  has_many :property_valuations, :dependent => :destroy
  has_many :properties, :through => :property_valuations 

  has_many :categorizations
  has_many :categories, :through => :categorizations

  # validations
  validates :name, :presence => true, :uniqueness => true
  validates :barcode, :uniqueness => true, :allow_nil => true, :allow_blank => true

  def as_json(options={})
    options[:except] ||= [:created_at, :updated_at]  
    #options[:include] ||= [:property_valuations]    
    super(options)
  end 

end

app/controllers/api/v1/items_controller.rb
module Api
  module V1
    class ItemsController < ApplicationController
      
      respond_to :json

      def index
        begin 
          category_id = params[:categoryId]
          barcode = params[:barcode]
            
          if (category_id)
            @items = Item.includes(:categories).where(:categories => { :id => category_id })
            @categories = Category.where("parent_id = ?", category_id)
            process_items_list_json(@items, @categories)
          elsif (barcode)
            @item = Item.where("barcode = ?", params[:barcode]).first
            
            if @item
              process_item_json(@item)
            else 
              raise ActiveRecord::RecordNotFound
            end
          else
            @items = []
            @categories = Category.where("parent_id IS NULL")
            process_items_list_json(@items, @categories)
          end              
          
        rescue ActiveRecord::RecordNotFound

          respond_with( {
            :statusCode => 1,
            :statusMessage => "Failed to process request"
          })

        end
      end

      def show
        begin
          @item = Item.find(params[:id])

          render :json => { 
            :statusCode => 0, 
            :statusMessage => 'Sucess',          
            :item => @item.as_json(
              :include => { :property_valuations => { :except  => [:id, :item_id, :property_id, :profile_id, :created_at, :updated_at], 
              :include => { :property => { :include => [:unit], :except => [:unit_id, :created_at, :updated_at] } }
              }})
          }
        rescue ActiveRecord::RecordNotFound
          respond_with( {
            :statusCode => 1,
            :statusMessage => "Failed to get item"
          })
        end
      end

      def navigate        
        begin 
          category_id = params[:category_id]
                      
          if (category_id)
            puts "Filtering based on category id"
            @items = Item.includes(:categories).where(:categories => { :id => category_id })
            @categories = Category.where("parent_id = ?", category_id)            
          else
            @items = []
            @categories = Category.where("parent_id IS NULL")            
          end 

          if params[:rules]
            puts "Processing rules"
            @items = process_rules_filter(@items)
          else
            puts "No rules to process"
          end

          process_items_list_json(@items, @categories)
          
        rescue ActiveRecord::RecordNotFound
          
          respond_with( {
            :statusCode => 1,
            :statusMessage => "Failed to process request"
          })

        end
      end

      def search
        # parse parameters: keywords, categories, properties
        # params[:keywords]
        # params[:rules] = [{ "property_id": 1, "min_value": 1, "max_value": 2, "exact_value": null}]
        # params[:category_id]

        @items_list = []
        
        if (!params[:category_id] or params[:category_id] == -1)
          if (params[:keywords].to_s == '')
            @items_list = Item.all
          else            
            @items_list = Item.where("lower(items.name) like ?", "%#{params[:keywords].downcase}%")
          end          
        else

          @category = Category.find(params[:category_id])

          if (params[:keywords].to_s == '')
            @items_list = @category.items
          else                 
            @items_list = @category.items.where("lower(items.name) like ?", "%#{params[:keywords].downcase}%")
          end

          unless @category.blank?            
            @children_list = [@category]
            @items_list = @category.all_items(@children_list, @items_list, params[:keywords])
          end
        end

        if params[:rules]
          puts "Processing rules"
          @items_list = process_rules_filter(@items_list)
        else
          puts "No rules to process"
        end

        render :json => {
          :statusCode => 0, 
          :statusMessage => 'Sucess', 
          :items => @items_list
        }
      end

      def process_rules_filter(items_list)
        result = []

        items_list.each do |item|
          
          add_item = false

          params[:rules].each do |rule|            

            unless rule[:property_id].to_s == ''
              
              property_valuation = item.property_valuations.detect { |pv| pv.property.id == rule[:property_id] }
              
              if property_valuation and property_valuation.value.to_s != ''
                
                if rule[:exact_value].to_s != '' and rule[:exact_value].to_s != -1
                  if property_valuation.value.to_i == rule[:exact_value].to_i
                    add_item = true
                  else
                    add_item = false;
                    break;
                  end
                else

                  if rule[:min_value].to_s != '' and rule[:min_value].to_s != -1
                    if property_valuation.value.to_i >= rule[:min_value].to_i
                      add_item = true  
                    else
                      add_item = false
                      break;
                    end
                  end

                  if rule[:max_value].to_s != '' and rule[:max_value].to_s != -1
                    if property_valuation.value.to_i <= rule[:max_value].to_i
                      add_item = true
                    else
                      add_item = false
                      break;
                    end
                  end

                end

              end

            end            
          end

          result.push(item) if add_item == true

        end

        result
      end

      def process_item_json(items)
        render :json => { 
            :statusCode => 0, 
            :statusMessage => 'Sucess',          
            :item => items.as_json(
              :include => { :property_valuations => { :except  => [:id, :item_id, :property_id, :profile_id, :created_at, :updated_at], 
              :include => { :property => { :include => [:unit], :except => [:unit_id, :created_at, :updated_at] } }
              }})
          }
      end

      def process_items_list_json(items, categories)
        render :json => {
            :statusCode => 0, 
            :statusMessage => 'Sucess', 
            :categories => categories,
            :items => items.as_json(
              :include => { :property_valuations => { :except  => [:id, :item_id, :property_id, :profile_id, :created_at, :updated_at], 
              :include => { :property => { :include => [:unit], :except => [:unit_id, :created_at, :updated_at] } }
              }})          
          }
      end

    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  def save_item_properties
    @item.property_valuations.destroy_all

    if @inserted_properties
    
      @inserted_properties.keys.each do |key|              

        current_property = Property.find(key)
        
        if current_property
          @item.properties.push(current_property)  
          current_property_valuation = PropertyValuation.where('item_id = ? AND property_id = ?', @item.id, current_property.id).first
          current_property_valuation.value = @inserted_properties[key]
          current_property_valuation.save
        end
      end
    end
  end

  def get_available_properties
    if @inserted_properties and @inserted_properties.any?
     Property.where('id NOT IN (?)', @inserted_properties.keys.map { |p| p.id } )
    else
      Property.all
    end
  end

  def normalize_inserted_properties
    if @inserted_properties
      @new_inserted_properties = {}

      @inserted_properties.keys.each do |key|        
        @new_inserted_properties[Property.find(key)] = @inserted_properties[key]
      end

      @inserted_properties = @new_inserted_properties
    else
      @inserted_properties = {}
    end
  end

  def get_available_categories
    if @inserted_categories and @inserted_categories.any?
      Category.where('id NOT IN (?)', @inserted_categories)
    else
      Category.all
    end
  end

  def normalize_inserted_categories
    if @inserted_categories
      @new_inserted_categories = []

      @inserted_categories.each do |id|        
        @new_inserted_categories.push Category.find(id)
      end

      @inserted_categories = @new_inserted_categories
    else
      @inserted_categories = []
    end
  end

  def save_item_categories
    @item.categories.destroy_all

    if @inserted_categories
    
      @inserted_categories.each do |id|          
        current_category = Category.find(id)       
        if current_category 
          @item.categories.push(current_category)        
        end
      end
    end
  end

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
    @inserted_properties = {}
    @inserted_categories = []

    @item.property_valuations.each do |pv|
      @inserted_properties[pv.property_id] = pv.value
    end

    @available_properties = get_available_properties
    @available_categories = get_available_categories
  end

  def create
    @item = Item.new(params[:item])
    @inserted_properties = params[:insertedProperties]
    @inserted_categories = params[:insertedCategories]

    if @item.save 
      save_item_properties
      save_item_categories

      flash[:notice] = "Item has been created."
      redirect_to items_path
    else       

      normalize_inserted_properties
      normalize_inserted_categories

      @available_properties = get_available_properties
      @available_categories = get_available_categories

      flash[:alert] = "Item has not been created."
      render :action => "new"
    end
  end

  def edit
    @item = Item.find(params[:id])
    
    @inserted_properties = {}
    @inserted_categories = []
    
    @item.property_valuations.each do |pv|
      @inserted_properties[pv.property] = pv.value
    end

    @item.categories.each do |category|
      @inserted_categories.push category
    end

    @available_properties = get_available_properties 
    @available_categories = get_available_categories   
  end

  def update
    @item = Item.find(params[:id])
    @inserted_properties = params[:insertedProperties]
    @inserted_categories = params[:insertedCategories]

    if @item.update_attributes(params[:item])
      
      save_item_properties
      save_item_categories

      flash[:notice] = "Item has been updated"
      redirect_to items_path
    else

      normalize_inserted_properties
      normalize_inserted_categories

      @available_properties = get_available_properties
      @available_categories = get_available_categories

      flash[:alert] = "Item has not been updated"
      render :action => "new"
    end
  end

  def destroy
    @item = Item.find(params[:id])

    @item.destroy
    flash[:notice] = "Item has been deleted."
    redirect_to items_path
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_categories.html.erb
<h4>
  Categories
</h4>

<div id="availableCategoriesContainer" <% if @available_categories.empty? %> style="display: none;"<% end %>>
  <select id="categoryToAdd">
    <% @available_categories.each do |category| %>
      <option value="<%= category.id %>"><%= category.name %></option>
      <br/>
    <% end %>
  </select>

  <input type="button" value="Add" onclick="addCategory()" class="btn btn-fix"/>
</div>

<%= content_tag "table", id: "addedCategoriesTable", :class => 'table', 
    data: { categories: Category.all } do %>
  
  <tr>
      <th>Category</th>
      <th>Options</th>
  </tr>
  
  <tr id="categoryLineTemplate" class="template">
      <input type="hidden" name="" value="" />
      <td>Name</td>
      <td><%= link_to_function '', "removeCategory('Are you sure you want to dissociate this category?', #category_id#)", :class => 'icon-remove' %></td>
  <tr/>

  <% @inserted_categories.each do |category| %>
    <tr id="categoryLineTemplate<%= category.id %>">
      <input type="hidden" name="insertedCategories[]" value="<%= category.id %>" />
      <td><%= category.name %></td>
      <td><%= link_to_function '', "removeCategory('Are you sure you want to dissociate this category?', #{category.id})", :class => 'icon-remove' %></td>
    <tr/>
  <% end %>
                                    
<% end %>

app/views/items/_form.html.erb
<%= form_for @item do |f| %>

    <% if @item.errors.any? %>
        <div id="error_explanation">
        	<h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

        	<ul>
        		<% @item.errors.full_messages.each do |msg| %>
        		<li>
        			<%= msg %>
        		</li>
        		<% end %>
        	</ul>
        </div>
    <% end %>
    
    <p>
    	<%= f.label :name, "Item name" %>
    	<%= f.text_field :name %>
    </p>

    <p>
    	<%= f.label :description, "Description" %>
    	<%= f.text_area :description, :size => "50x6", :class => 'span12' %>
    </p>

    <p>
        <%= f.label :barcode, "Barcode:" %>
        <%= f.text_field :barcode %>
    </p>
    
    <hr />

    <%= render "categories" %>
    
    <hr />

    <%= render "properties" %>

    <%= f.submit 'Save', :class => 'btn btn-success' %>
    <%= link_to 'Cancel', items_path, :data => { :confirm => 'Are you sure you want to leave this page?' }, :class => 'btn btn-danger' %>
<% end %>

app/views/items/_properties.html.erb
<h4>
  Properties
</h4>

  
<div id="availablePropertiesContainer" <% if @available_properties.empty? %> style="display: none;"<% end %>>
  <select id="propertyToAdd" onchange="refreshUnitText()">
    <% @available_properties.each do |property| %>
      <option value="<%= property.id %>"><%= property.name %></option>
      <br/>
    <% end %>
  </select>

  <input id="propertyValue" type="text" class="input-small" />
  <p id="propertyType" style="display: inline;"></p>   
  <input type="button" value="Add" onclick="addProperty()" class="btn btn-fix"/>
  <p id="invalidValueError">Value not allowed!</p>
</div>


<%= content_tag "table", id: "addedPropertiesTable", :class => 'table', 
    data: { properties: Property.all } do %>
  
  <tr>
      <th>Property</th>
      <th>Value</th>
      <th>Options</th>
  </tr>
  
  <tr id="propertyLineTemplate" class="template">
      <input type="hidden" name="" value="" />
      <td>Name</td>
      <td>Value</td>
      <td><%= link_to_function '', "removeProperty('Are you sure you want to dissociate this property?', #property_id#)", :class => 'icon-remove' %></td>
  <tr/>

  <% @inserted_properties.each_key do |property| %>
    <tr id="propertyLineTemplate<%= property.id %>">
      <input type="hidden" name="insertedProperties[<%= property.id %>]" value="<%= @inserted_properties[property] %>" />
      <td><%= property.name %></td>
      <td><%= @inserted_properties[property] %></td>
      <td><%= link_to_function '', "removeProperty('Are you sure you want to dissociate this property?', #{property.id})", :class => 'icon-remove' %></td>
    <tr/>
  <% end %>
                                    
<% end %>

app/views/items/edit.html.erb
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "items.js" %>
<% end %>

<h2>Edit Item</h2>

<hr />

<%= render "form" %>

app/views/items/index.html.erb
<h2>Items</h2>

<hr />

<%= link_to "New Item", new_item_path, :class => 'btn btn-primary' %>

<br /><br />

<% if @items.any? %>
    <table class="table table-striped">
        <tr>            
            <th>Name</th>
            <th>Description</th>            
            <th colspan="3">Options</th>
        </tr>
    
        <% @items.each do |item| %>
            <tr>                
                <td><%= item.name %></td>
                <td><%= item.description %></td>                
                <td><%= link_to '', item_path(item), :class => 'icon-eye-open' %></td>
                <td><%= link_to '', edit_item_path(item), :class => 'icon-pencil' %></td>
                <td><%= link_to '', item, :method => :delete,
      :data => { :confirm => "Are you sure you want to delete this item?" }, :class => 'icon-remove' %></td>
            </tr>
        <% end %>
    
    </table>
<% else %>
    <p>There are no items yet.</p>
<% end %>

app/views/items/new.html.erb
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "items.js" %>
<% end %>

<h2>New item</h2>

<hr />

<%= render "form" %>

app/views/items/show.html.erb
<h2>Item</h2>

<p>Name: <%= 	@item.name %></p>
<p>Description: <%= @item.description %></p>

<%= link_to "Edit Item", edit_item_path(@item), :class => 'btn btn-primary' %>
<%= link_to "Delete Item", @item, 
    :method => :delete, :class => 'btn btn-danger', :data => { :confirm => 'Are you sure you want to delete this item?'} %>