config/routes.rb
SPIN::Application.routes.draw do
  
  resources :property_ranges
  resources :profiles
  resources :units
  resources :categories
  resources :properties
  resources :items

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :property_ranges
      resources :profiles
      resources :units
      resources :categories
      resources :properties
      resources :items do
        post 'search', :on => :collection
        post 'navigate', :on => :collection
      end 

    end
  end

  

  root :to => 'pages#index'

  match 'index' => 'pages#index'
  match 'about' => 'pages#about'    
  
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  attr_accessible :name

  has_many :properties, :dependent => :destroy

  # validations
  validates :name, :presence => true, :uniqueness => true

    # exclude fields from json output
  def as_json(options={})
    options[:except] ||= [:created_at, :updated_at]
    super(options)
  end 
end

app/controllers/api/v1/units_controller.rb
module Api
  module V1
    class UnitsController < ApplicationController

      respond_to :json

      def index
        @units = Unit.all

        render :json => { 
          :statusCode => 0, 
          :statusMessage => 'Sucess', 
          :units => @units
        }
         
      end
      
      def show
        begin
          @unit = Unit.find(params[:id])
        rescue ActiveRecord::RecordNotFound
          respond_with( {
            :statusCode => 1,
            :statusMessage => "Failed to get unit"
          })
        end
      end    
        
    end
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController

  def index
    @units = Unit.all
  end
  
  def show
    @unit = Unit.find(params[:id])
  end    
  
  def new
    @unit = Unit.new    
  end 
    
  def create
    @unit = Unit.new(params[:unit])
    
    if @unit.save
      flash[:notice] = "Unit has been created."
      redirect_to units_path
    else
      flash[:alert] = "Unit has not been created."
      render :action => "new"
    end
  end
  
  def edit
    @unit = Unit.find(params[:id])
  end
  
  def update        
    @unit = Unit.find(params[:id])
        
    if @unit.update_attributes(params[:unit])
      flash[:notice] = "Unit has been updated"
      redirect_to units_path
    else
      flash[:alert] = "Unit has not been updated"
      render :action => "edit"
    end
  end   
  
  def destroy
    @unit = Unit.find(params[:id])
    
    @unit.destroy
    flash[:notice] = "Unit has been deleted."
    redirect_to units_path
  end

end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
<%= form_for(@unit) do |f| %>
<% if @unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
      <% @unit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	
  <p>
		<%= f.label :name, "Unit name" %>
		<%= f.text_field :name %>
	</p>
	
	<%= f.submit :class => 'btn btn-success' %>
	<%= link_to 'Cancel', units_path, :data => { :confirm => 'Are you sure you want to leave this page?' }, :class => 'btn btn-danger' %>

<% end %>

app/views/units/edit.html.erb
<h2>Edit Unit</h2>

<hr />

<%= render "form" %>

app/views/units/index.html.erb
<h2>Units</h2>

<hr />

<%= link_to "New Unit", new_unit_path, :class => 'btn btn-primary' %>

<br /><br />

<% if @units.any? %>
    <table class="table table-striped">
        <tr>            
            <th>Name</th>
            <th colspan="3">Options</th>            
        </tr>
    
        <% @units.each do |unit| %>
            <tr>                
                <td><%= unit.name %></td>
                <td><%= link_to '', unit_path(unit), :class => 'icon-eye-open' %></td>
                <td><%= link_to '', edit_unit_path(unit), :class => 'icon-pencil' %></td>
                <td><%= link_to '', unit, :method => :delete, 
                        :data => { :confirm => "Are you sure you want to delete this unit?" }, :class => 'icon-remove' %></td>

            </tr>
        <% end %>
    
    </table>
<% else %>
    <p>There are no units yet.</p>
<% end %>

app/views/units/new.html.erb
<h2>New Unit</h2>

<hr />

<%= render "form" %>

app/views/units/show.html.erb
<h2>Property</h2>

<p><%= @property.name %></p>
<p><%= @property.description %></p>
<p><%= @property.value_type %></p>
<p><%= @property.unit %></p>

<%= link_to "Edit Property", edit_property_path(@property), :class => 'btn btn-primary' %>
<%= link_to "Delete Property", @property, :method => :delete, :class => 'btn btn-danger',
    :data => { :confirm => 'Are you sure you want to delete this property?' } %>