config/routes.rb
SPIN::Application.routes.draw do
  
  resources :property_ranges
  resources :profiles
  resources :units
  resources :categories
  resources :properties
  resources :items

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :property_ranges
      resources :profiles
      resources :units
      resources :categories
      resources :properties
      resources :items do
        post 'search', :on => :collection
        post 'navigate', :on => :collection
      end 

    end
  end

  

  root :to => 'pages#index'

  match 'index' => 'pages#index'
  match 'about' => 'pages#about'    
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :description, :parent, :children, :items, :parent_id
  
  has_many :children, :class_name => "Category", :foreign_key => "parent_id", :dependent => :nullify
  belongs_to :parent, :class_name => "Category"
   
  has_many :categorizations
  has_many :items, :through => :categorizations

  # validations
  validates :name, :presence => true, :uniqueness => true
  
  def all_children(children_array = [], name_filter = '', rules_filter)

    if name_filter.to_s == ''
      child_categories = Category.where(:parent_id => self.id).includes(:items)
    else      
      child_categories = Category.where(:parent_id => self.id).includes(:items).where("lower(items.name) like ?", "%#{name_filter.downcase}%")
    end
    
    children_array += child_categories.all
    child_categories.each do |child|      
      children_array = child.all_children(children_array, name_filter)
    end

    children_array    
  end

  def as_json(options={})
    options[:except] ||= [:created_at, :updated_at]
    super(options)
  end 



  def all_items(children_array = [], items_list = [], name_filter = '')
    puts "name_filter: #{name_filter}" 


    @child_items = []
    child_categories = Category.where(:parent_id => self.id)

    #puts "=============child_categories============="
    #puts child_categories.inspect

    child_categories.each do |child_category|
      if name_filter.to_s == ''        
        @child_items = child_category.items
      else        
        @child_items = child_category.items.where("lower(items.name) like ?", "%#{name_filter.downcase}%")
      end

      #puts "=============child_items============="
      #puts @child_items.inspect
      
      # add child items to list
      @child_items.each do |item|
         items_list << item unless items_list.include?(item)
      end
    end    

    #puts "=============items_list============="
    #puts items_list.inspect

    children_array += child_categories.all
    
    child_categories.each do |child|
      items_list = child.all_items(children_array, items_list, name_filter)      
    end                        

    items_list    
  end

  def as_json(options={})
    options[:except] ||= [:created_at, :updated_at]
    super(options)
  end 
end

app/controllers/api/v1/categories_controller.rb
module Api
  module V1
    class CategoriesController < ApplicationController

      respond_to :json
      
      def index
        @categories = Category.all 

        respond_with( {
          :statusCode => 0,
          :statusMessage => "Success",
          :categories => @categories
          })
      end

      def show
        begin
          @category = Category.find(params[:id])

          respond_with( {
            :statusCode => 0,
            :statusMessage => "Success",
            :category => @category
          })

        rescue ActiveRecord::RecordNotFound
          respond_with( {
            :statusCode => 1,
            :statusMessage => "Failed to get category"
          })
        end
      end
      
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
    @available_categories = Category.all;
  end

  def create
    @category = Category.new(params[:category])
    @available_categories = Category.all;

    if @category.save
      flash[:notice] = "Category has been created."
      redirect_to categories_path
    else
      flash[:alert] = "Category has not been created."
      render :action => "new"
    end
  end

  def edit
    @category = Category.find(params[:id])    
    @available_categories = Category.where('id <> ?', params[:id]);
  end

  def update
    @category = Category.find(params[:id])
    @available_categories = Category.where('id <> ?', params[:id]);

    if @category.update_attributes(params[:category])
      flash[:notice] = "Category has been updated"
      redirect_to categories_path
    else
      flash[:alert] = "Category has not been updated"
      render :action => "new"
    end

  end

  def destroy
    @category = Category.find(params[:id])

    @category.destroy
    flash[:notice] = "Item has been deleted."
    redirect_to categories_path
  end
  
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
<% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<p>
		<%= f.label :name, "Category name" %>
		<%= f.text_field :name %>
	</p>

 
    <p>
      <%= f.label :parent_id, "Parent category" %>
      <%= f.collection_select :parent_id, @available_categories, :id, :name, {:include_blank => "Select parent category..."} %>
    </p>

	
	<p>
		<%= f.label :description, "Description" %>
		<%= f.text_area :description, :size => "50x6", :class => 'span12' %>
	</p>  
  	
	<%= f.submit :class => 'btn btn-success' %>
	<%= link_to 'Cancel', categories_path, :data => { :confirm => 'Are you sure you want to leave this page?'}, :class => 'btn btn-danger' %>

<% end %>

app/views/categories/edit.html.erb
<h2>Edit category</h2>

<hr />

<%= render "form" %>

app/views/categories/index.html.erb
<h2>Categories</h2>

<hr />

<%= link_to "New Category", new_category_path, :class => 'btn btn-primary' %>

<br /><br />

<% if @categories.any? %>
    <table class="table table-striped">
        <tr>            
            <th>Name</th>
            <th>Parent</th>
            <th>Description</th>
            <th colspan="3">Options</th>
        </tr>
    
        <% @categories.each do |category| %>
            <tr>                
                <td><%= category.name %></td>
                <td><%= category.parent.name if category.parent %></td>
                <td><%= category.description %></td>
                <td><%= link_to '', category_path(category), :class => 'icon-eye-open' %></td>
                <td><%= link_to '', edit_category_path(category), :class => 'icon-pencil' %></td>
                <td><%= link_to '', category, :method => :delete, 
                :data => { :confirm => "Are you sure you want to delete this category?" }, :class => 'icon-remove' %></td>

            </tr>
        <% end %>
    
    </table>
<% else %>
    <p>There are no categories yet.</p>
<% end %>

app/views/categories/new.html.erb
<h2>New category</h2>

<hr />

<%= render "form" %>

app/views/categories/show.html.erb
<h2>Category</h2>

<p><%= @category.name %></p>
<p><%= @category.description %></p>

<%= link_to "Edit Category", edit_category_path(@category), :class => 'btn btn-primary' %>
<%= link_to "Delete Category", @category, :method => :delete, :class => 'btn btn-danger',
    :data => { :confirm => 'Are you sure you want to delete this category?' } %>
  